feat(home): about section
Fundacja-Sterczace-Uszy/website pull request #110
Opened 2023-03-16 06:31 UTC by paulgrym

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description

## Jira issue

JIRA issue: [FSU-112](https://klau.atlassian.net/browse/FSU-112)

## Describe your changes

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2023-03-16 09:11 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/AboutSection/AboutSection.jsx
> +          </Typography>
Maybe a better idea would be to wrap Typography into some container and then add some gap between text instead of using many `<br>` tags? :D

2023-03-16 09:11 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/AboutSection/AboutSection.styled.js
> +    padding-bottom: 60px;
```suggestion
   padding: 60px 0;
```

2023-03-16 09:11 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/AboutSection/AboutSection.styled.js
> +    padding-bottom: 100px;
```suggestion
padding: 100px 0;
```

2023-03-16 17:25 UTC, paulgrym commented on packages/frontend/app/templates/HomePage/components/AboutSection/AboutSection.jsx
> +          </Typography>
Great suggestion! Done 😄

2023-03-16 17:28 UTC, AmandaKr approved these changes
perfect ❤️

2023-03-16 18:03 UTC, Ebmili approved these changes
Good to go :)

2023-03-17 09:07 UTC, im-klau requested changes

2023-03-17 09:07 UTC, im-klau commented on packages/frontend/app/templates/HomePage/HomePage.jsx
>  import Achievements from "./components/Achievements"
The env.example file is deleted but it's important to keep it in our repo so that everyone knows what envs are needed to build the app :D

![Zrzut ekranu 2023-03-17 o 09 57 06](https://user-images.githubusercontent.com/78494852/225859519-014c8fc2-ae8e-4f39-b831-bcf689cdca89.png)

2023-03-17 09:07 UTC, im-klau commented on packages/frontend/app/templates/HomePage/HomePage.jsx
> +import AboutSection from "./components/AboutSection/AboutSection"
Let's maybe keep the names as simple as they can be, so just "About" would be totally fine 🙏 It's not wrong right now, but it can be more readable

This way, we'll avoid something like this:
```jsx
<main>
  <HeroSection />
  <AboutSection />
  <AnimalsSection />
  <SupportSection />
  <SupportersSection />
</main>
```

towards:
```jsx
<main>
   <Hero />
   <About />
   <Animals />
   <Support />
   <Supporters />
</main>

2023-03-18 11:43 UTC, nata-kab approved these changes
Looks great 🚀

2023-03-19 07:33 UTC, im-klau approved these changes
❤️ 🎉

2023-03-19 11:42 UTC, merged