feat: introduce adoption section, creating adoption
Fundacja-Sterczace-Uszy/website pull request #111
Opened 2023-03-18 15:28 UTC by Ebmili

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description

## Jira issue

## Describe your changes

Hi, 

I am creating PR for the Adoption section. 

Look forward to your review :)

2023-03-18 20:11 UTC, AmandaKr requested changes
You have changed the PR structure, look at other PRs in our repository, you can add a link to Jira there, now you have removed our template and the tests did not pass :(

2023-03-18 20:11 UTC, AmandaKr commented on packages/frontend/app/templates/Adoption/Adoption.styled.js
> +  height: 100%;
I recommend you to simplify the styles you used. You can use only flex and add some margins/padding to sections. You don't need any position: absolute, width: 80% etc.

2023-03-18 20:11 UTC, AmandaKr commented on packages/frontend/app/templates/Adoption/Adoption.jsx
> +                  text="Przeanalizuj"
I see that font-family here is Times New Roman. It should be Poppins 🤔

2023-03-18 20:11 UTC, AmandaKr commented on packages/frontend/app/templates/Adoption/Adoption.jsx
> +                  className={null}
```suggestion
```

2023-03-18 20:11 UTC, AmandaKr commented on packages/frontend/app/templates/Adoption/Adoption.jsx
> +                  className={null}
If you don't need `classname`, you don't have to add this. (className is optional prop)

2023-03-18 20:11 UTC, AmandaKr commented on packages/frontend/app/templates/Adoption/Adoption.styled.js
> +    align-items: center;
flex properties is mixed here with grid

2023-03-18 20:11 UTC, AmandaKr commented on packages/frontend/app/templates/Adoption/Adoption.jsx
> +            <Typography variant="h2" color={theme.colors.grey[700]}>
![image](https://user-images.githubusercontent.com/97829893/226135928-9e11ce36-2034-4bc1-a198-f647221e13c9.png)
This section should be centered on mobile view also

2023-03-18 20:13 UTC, AmandaKr commented on packages/frontend/app/templates/Adoption/Adoption.jsx
> +                  text="Przeanalizuj"
![image](https://user-images.githubusercontent.com/97829893/226136124-04ad2d4c-391e-4ea9-87a6-ee0f24de0b24.png)

2023-03-18 20:19 UTC, AmandaKr commented on packages/frontend/app/templates/Adoption/Adoption.jsx
> +            <Typography variant="h2" color={theme.colors.grey[700]}>
color  of this heading should be gray[600]

2023-03-19 07:28 UTC, im-klau commented on packages/frontend/app/templates/Adoption/Adoption.jsx
> +              href="/Sprawdz warunki adopcji"
or `/adopcja` as our URLs will be Polish :D

2023-03-19 07:30 UTC, im-klau commented on packages/frontend/app/templates/Adoption/Adoption.jsx
> +                  text="Przeanalizuj"
We can omit this one as this is Title's bug and I fixed the issue in another PR:)

2023-03-19 07:31 UTC, im-klau commented on packages/frontend/app/templates/Adoption/Adoption.jsx
> +            <Typography variant="h2" color={theme.colors.grey[700]}>
Actually, instead of using multiple Typography components, you can use `TextBanner` here @Ebmili

2023-03-19 11:18 UTC, closed without merging