Fsu 114 adoption section
Fundacja-Sterczace-Uszy/website pull request #114
Opened 2023-03-19 11:45 UTC by Ebmili

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description

## Jira issue

JIRA issue: [FSU-XX](https://klau.atlassian.net/browse/FSU-XX)

## Describe your changes

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2023-03-20 08:26 UTC, AmandaKr requested changes

2023-03-20 08:26 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    text-align: center;
You don't need this property because you have layout "center "on `Card` and `TextBanner` component

2023-03-20 08:26 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +  position: relative;
Redundant prop

2023-03-20 08:26 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    margin-bottom: 10px;
```suggestion
margin: 1px 0 10px;
```

2023-03-20 08:26 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    margin-bottom: 10px;
But anyway: Do we really need margin: 1px here?

2023-03-20 08:26 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +  text-align: center;
```suggestion
```

2023-03-20 08:26 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +  position: relative;
```suggestion
```

2023-03-20 08:26 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    margin: 140px auto;
Reduntant prop, because of the same margins in tabletLg

2023-03-20 08:26 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    display: grid;
If you want to use grid, you shouldn't pass flex-direction here
Maybe better idea would be use display: flex?

2023-03-20 08:26 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    align-items: center;
in `RulesContainer`, remove align-items: center in tabletLg and mobileLg view, because it's inherited from desktop view

2023-03-20 08:26 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    flex-direction: column;
```suggestion
```

2023-03-20 08:26 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +  margin-top: 10px;
You have to decide which margin you need :D

2023-03-20 08:26 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    margin-top: 1px;
```suggestion
```

2023-03-20 08:26 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    flex-direction: column;
```suggestion
```

2023-03-20 08:26 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.jsx
> +            formy wsparcia. Jeżeli chcesz czynić dobro sprawdz, co możesz
```suggestion
            formy wsparcia. Jeżeli chcesz czynić dobro sprawdź, co możesz
```

2023-03-20 08:47 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    text-align: center;
deleted

2023-03-20 08:48 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    display: grid;
done

2023-03-20 08:54 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +  text-align: center;
@AmandaKr I think I need this one, as otherwise my rules text is not centered.

2023-03-20 09:13 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +  position: relative;
deleted

2023-03-20 09:15 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    margin-bottom: 10px;
deleted

2023-03-20 09:17 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +  margin-top: 10px;
I left  margin: 0 auto :)

2023-03-20 09:17 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    margin-top: 1px;
deleted

2023-03-20 09:18 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    flex-direction: column;
done

2023-03-20 09:18 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.jsx
> +            formy wsparcia. Jeżeli chcesz czynić dobro sprawdz, co możesz
done

2023-03-20 10:35 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    flex-direction: column;
done

2023-03-20 13:12 UTC, im-klau commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +  background-color: ${({ theme }) => theme.colors.neutrals[100]};
I'm not sure if you need to set the background color to white as the whole page is white 🤔

2023-03-20 14:45 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    display: flex;
```suggestion
```

2023-03-21 09:29 UTC, im-klau commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    flex-direction: column;
there's no `display: flex` in this component so flex-direction isn't needed

2023-03-21 20:41 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    display: flex;
@AmandaKr Done

2023-03-21 20:54 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +    flex-direction: column;
@im-klau I deleted this

2023-03-21 20:55 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +`
@im-klau I think I got confused with some your previous comment, nevermind, deleted it :)

2023-03-21 20:55 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +export const Main = styled.main`
@im-klau Got it, deleted

2023-03-22 07:32 UTC, AmandaKr commented
great job 🚀 only linting failes so you can use` yarn lint:fix ` and add some commit to resolve it :)

2023-03-22 07:34 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +  text-align: center;
add some margins here also to separate sections

2023-03-22 10:47 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Adoption/Adoption.styled.js
> +  text-align: center;
@AmandaKr Done :)

2023-03-22 12:17 UTC, AmandaKr approved these changes

2023-03-22 12:46 UTC, im-klau approved these changes
Well done! 🎉 🎉

2023-03-22 17:37 UTC, nata-kab approved these changes
Looks great  🤩 🚀

2023-03-23 09:22 UTC, merged