Fsu 145 achievements section
Fundacja-Sterczace-Uszy/website pull request #117
Opened 2023-03-20 16:25 UTC by nata-kab

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description

## Jira issue

JIRA issue: [FSU-145](https://klau.atlassian.net/browse/FSU-145)

## Describe your changes

 In progress

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2023-03-23 17:07 UTC, im-klau commented on packages/frontend/app/templates/HomePage/components/Achievements/Achievements.jsx
> +      subtitle="FUNDACJA W LICZBACH"
```suggestion
      subtitle="Fundacja w liczbach"
```

2023-03-24 09:32 UTC, im-klau requested changes
I've found just one, small issue but other than that the section looks perfect ❤️ Amazing work! 🙌

2023-03-24 09:32 UTC, im-klau commented on packages/frontend/app/templates/HomePage/components/Achievements/Achievements.styled.js
> +    padding: 60px 14px;
You don't need to set tablet and mobile horizontal paddings as the `Container` that's around this section adds them anyway. So now, you have duplicated paddings.

2023-03-24 12:30 UTC, AmandaKr commented on packages/frontend/app/templates/HomePage/components/Achievements/Achievements.styled.js
> +  display: flex-inline;
```suggestion
  display: inline-flex;
```

2023-03-24 22:39 UTC, nata-kab commented on packages/frontend/app/templates/HomePage/components/Achievements/Achievements.styled.js
> +    padding: 60px 14px;
Done 😀

2023-03-25 06:48 UTC, paulgrym approved these changes
🚀

2023-03-25 10:05 UTC, im-klau approved these changes

2023-03-25 10:10 UTC, merged