feat(about): add aboutUs section
Fundacja-Sterczace-Uszy/website pull request #118
Opened 2023-03-20 19:43 UTC by AmandaKr

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description

## Jira issue

JIRA issue: [FSU-129](https://klau.atlassian.net/browse/FSU-129)

## Describe your changes
aboutUs sedction in progress

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2023-03-22 13:00 UTC, im-klau requested changes
Just a few comments 🙌

2023-03-22 13:00 UTC, im-klau commented on packages/frontend/app/templates/About/components/AboutUs/AboutUs.jsx
> +      <Styled.Wrapper>
Comparing to the design, the left column should be smaller and the right one a bit larger.

Preview:
![Zrzut ekranu 2023-03-22 o 13 58 22](https://user-images.githubusercontent.com/78494852/226911797-a8e09beb-bbd4-4548-bd1e-6a0ecdb1e9f9.png)

Design:
![Zrzut ekranu 2023-03-22 o 13 58 32](https://user-images.githubusercontent.com/78494852/226911815-05f3cfae-1e6c-422c-8e8b-aa092df13e14.png)

2023-03-22 14:31 UTC, im-klau commented on packages/frontend/app/public/home/aboutus-section-image.png
this png should be in a separated directory "about", inside `public`

2023-03-22 14:32 UTC, im-klau commented on packages/frontend/app/templates/About/components/AboutUs/AboutUs.styled.js
> +  object-fit: cover;
the `object-fit: cover` is already applied to the Image component so you can get rid of it here

2023-03-22 14:33 UTC, im-klau commented on packages/frontend/app/templates/About/components/AboutUs/AboutUs.styled.js
> +    object-fit: cover;
same with this object-fit

2023-03-22 16:03 UTC, paulgrym approved these changes
Great job! 🌟

2023-03-22 16:08 UTC, paulgrym commented on packages/frontend/app/templates/About/components/AboutUs/AboutUs.styled.js
> +  margin-top: 200px;
Oh I jus spotted that in design there is no margin-top. But without it the photo is not heigh enough so I would remove `height:700px;` and add max-width or some grid 🤔

2023-03-23 08:03 UTC, Ebmili approved these changes
Looks great :)

2023-03-23 09:33 UTC, im-klau commented on packages/frontend/app/templates/About/components/AboutUs/AboutUs.styled.js
> +  margin-top: 200px;
@AmandaKr just one, additional comment, and once it's resolved we can merge it 🚀

2023-03-23 10:29 UTC, AmandaKr commented on packages/frontend/app/templates/About/components/AboutUs/AboutUs.styled.js
> +  margin-top: 200px;
@im-klau  I'll correct it before today's daily and will merge it

2023-03-24 22:54 UTC, nata-kab approved these changes
I found nothing to fix 🕵️‍♀️ 🤣  Simply looks perfect ❤️ Great job 🙌

2023-03-25 11:30 UTC, im-klau approved these changes

2023-03-25 11:46 UTC, merged