feat: create for-adoption page setup
Fundacja-Sterczace-Uszy/website pull request #125
Opened 2023-03-26 11:19 UTC by AmandaKr

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description

## Jira issue

JIRA issue: [FSU-165](https://klau.atlassian.net/browse/FSU-165)

## Describe your changes

This PR introduces basic Next.js setup for a new "For adoption" page.

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2023-03-26 11:39 UTC, paulgrym approved these changes
The subpage exists under good url, there is a header and a footer so I think it all we need 😄

2023-03-26 20:21 UTC, Ebmili commented
Well Done :)

2023-03-26 20:22 UTC, Ebmili approved these changes

2023-03-27 08:29 UTC, im-klau requested changes

2023-03-27 08:29 UTC, im-klau commented on packages/frontend/app/pages/do-adopcji.jsx
> +      supporting: supporting.supportingCollection,
I guess this page only needs the `animals` data. You can get rid of the rest of them.

2023-03-27 08:29 UTC, im-klau commented on packages/frontend/app/templates/Adoption/Adoption.jsx
> +    <Footer />
According to the Jira ticket, the contact banner should be included as well :D

2023-03-27 08:50 UTC, AmandaKr commented on packages/frontend/app/templates/Adoption/Adoption.jsx
> +    <Footer />
ohh, right, I thought it was about the banner at the top :D

2023-03-27 16:28 UTC, im-klau approved these changes
🚀

2023-03-27 16:30 UTC, merged