Fsu 151 values section
Fundacja-Sterczace-Uszy/website pull request #128
Opened 2023-03-30 18:40 UTC by Ebmili

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description

## Jira issue

JIRA issue: [FSU-XX](https://klau.atlassian.net/browse/FSU-XX)

## Describe your changes

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2023-04-01 15:16 UTC, AmandaKr commented
Please update your PR description correctly and check lint issues 🙏

2023-04-02 11:02 UTC, Ebmili commented
> Please update your PR description correctly and check lint issues 🙏

It's done :)

2023-04-02 12:09 UTC, paulgrym requested changes

2023-04-02 12:09 UTC, paulgrym commented on packages/frontend/app/templates/About/components/Values/Values.jsx
> +        </Styled.TextWrapper>
This should be TextBanner child

2023-04-02 12:09 UTC, paulgrym commented on packages/frontend/app/templates/About/components/Values/Values.jsx
> +        </Styled.TextWrapper>
And whole TextBanner should have set max-width on tablet view

2023-04-02 12:09 UTC, paulgrym commented on packages/frontend/app/templates/About/components/Values/Values.jsx
> +        </Styled.TextBottomWrapper>
This also should have max-width on tablet view and should be variant="h5" instead of being wrapped in <strong>

2023-04-02 12:09 UTC, paulgrym commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +export const Featurecomp = styled.div`
That styled component name doesn't fit to the naming convention in this project. It should be in camel case and not a shortcut - e.g. `FeatureComponent`

2023-04-02 12:59 UTC, AmandaKr requested changes
![image](https://user-images.githubusercontent.com/97829893/229354267-ec36c18e-a6f6-42d2-b723-5e9321dbd784.png)
Image does not display, perhaps the path is misspecified
In addition, at a resolution of about 600px the text overlaps. I think changing it to TextBanner and some gap will help :D.

2023-04-02 12:59 UTC, AmandaKr commented on packages/frontend/app/templates/About/components/Values/Values.jsx
> +        </Styled.TextWrapper>
And TextBanner should have mobile and tablet layout set to left :D

2023-04-02 12:59 UTC, AmandaKr commented on packages/frontend/app/templates/About/components/Values/Values.jsx
> +              icon="trust"
Let's use a map here instead of repeating the same element many times

2023-04-02 12:59 UTC, AmandaKr commented on packages/frontend/app/templates/About/components/Values/Values.jsx
> +        <Styled.Img alt="dog with heart" src="../values/values.png" />
and the name of the photo should be in lowercase because it is not svg

2023-04-02 14:33 UTC, Ebmili commented on packages/frontend/app/templates/About/components/Values/Values.jsx
> +        <Styled.Img alt="dog with heart" src="../values/values.png" />
@paulgrym @AmandaKr  this is done

2023-04-02 14:34 UTC, Ebmili commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +`
@paulgrym done

2023-04-02 14:35 UTC, Ebmili commented on packages/frontend/app/templates/About/components/Values/Values.jsx
> +        </Styled.TextWrapper>
@AmandaKr @paulgrym this is done

2023-04-02 14:47 UTC, Ebmili commented on packages/frontend/app/templates/About/components/Values/Values.jsx
> +        </Styled.TextBottomWrapper>
@paulgrym this is done

2023-04-02 14:47 UTC, Ebmili commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +export const Featurecomp = styled.div`
@paulgrym Corrected

2023-04-02 14:48 UTC, Ebmili commented
> [packages/frontend/app/templates/About/components/Values/Values.jsx](/Fundacja-Sterczace-Uszy/website/pull/128/files/6645d8457e46334c02c4fb1af7b6a68c638ca329#diff-59e20d5e77164df58066e72d940c1c593d1682b9a276ca23da7861b55345a0e6)

@AmandaKr Could you please check now? I just double checked and it is displaying for me on every device :O

2023-04-02 15:26 UTC, AmandaKr commented
> > [packages/frontend/app/templates/About/components/Values/Values.jsx](/Fundacja-Sterczace-Uszy/website/pull/128/files/6645d8457e46334c02c4fb1af7b6a68c638ca329#diff-59e20d5e77164df58066e72d940c1c593d1682b9a276ca23da7861b55345a0e6)
> 
> @AmandaKr Could you please check now? I just double checked and it is displaying for me on every device :O

Yes it's working now :D

2023-04-02 17:25 UTC, Ebmili commented on packages/frontend/app/templates/About/components/Values/Values.jsx
> +              icon="trust"
@AmandaKr This is done :)

2023-04-02 19:00 UTC, AmandaKr commented on packages/frontend/app/templates/About/components/Values/Values.jsx
> +              <Feature key={heading} description={description} icon={icon} />
heading is missing here 👀 
![image](https://user-images.githubusercontent.com/97829893/229373293-8a96ad99-59ad-4206-9424-6be4df8cde9f.png)

2023-04-02 19:32 UTC, Ebmili commented on packages/frontend/app/templates/About/components/Values/Values.jsx
> +              <Feature key={heading} description={description} icon={icon} />
@AmandaKr Sorry it's back again :)

2023-04-03 08:11 UTC, AmandaKr reviewed
Well done, only one thing to add: I see that this section has a gradient for the background 👀

2023-04-03 16:26 UTC, paulgrym requested changes
Text hides under scrollbar:
![image](https://user-images.githubusercontent.com/87578610/229569834-9084d275-70da-45a9-9529-12a5fac0efbd.png)

This text should have limited width:
![image](https://user-images.githubusercontent.com/87578610/229570153-4bf87fd8-1144-4773-8284-e33e61ee5fca.png)

Image on tablet and mobile should have smaller height:
![image](https://user-images.githubusercontent.com/87578610/229570422-9ebd6b75-2984-466b-9fd7-f45aa802fcb0.png)

2023-04-03 19:30 UTC, Ebmili commented
> Well done, only one thing to add: I see that this section has a gradient for the background 👀

It's added now :)

2023-04-03 19:32 UTC, Ebmili commented
> Text hides under scrollbar: ![image](https://user-images.githubusercontent.com/87578610/229569834-9084d275-70da-45a9-9529-12a5fac0efbd.png)
> 
> This text should have limited width: ![image](https://user-images.githubusercontent.com/87578610/229570153-4bf87fd8-1144-4773-8284-e33e61ee5fca.png)
> 
> And this as well: ![image](https://user-images.githubusercontent.com/87578610/229570661-02e637eb-f090-4705-a21d-2ae92f9d53b3.png)
> 
> Image on tablet and mobile should have smaller height: ![image](https://user-images.githubusercontent.com/87578610/229570422-9ebd6b75-2984-466b-9fd7-f45aa802fcb0.png)

Hi, I updated max width and images and I think I took the smallest possible size :) Let me know if this looks better now : )

2023-04-03 20:13 UTC, im-klau commented on packages/frontend/app/templates/About/components/Values/Values.jsx
> +        <Styled.Img alt="dog for values section" src="../about/values.png" />
```suggestion
        <Styled.Img alt="" src="../about/values.png" />
```
Let's leave the alt empty for now, as the image is decorative in this section.

2023-04-03 20:14 UTC, im-klau commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +    padding-bottom: 100px;
padding-bottom has the same value declared above so there's no need to duplicate it here

2023-04-03 20:14 UTC, im-klau commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +    margin-bottom: 10px;
margin-bottom has the same value (10px) declared above so there's no need to duplicate it here

2023-04-03 20:15 UTC, im-klau commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +    grid-template-columns: 1fr;
the `grid-template-columns: 1fr` property is declared above, so you don't need it here

2023-04-03 20:19 UTC, im-klau commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +  background: linear-gradient(0deg, #eeeeee 0%, rgba(255, 255, 255, 0) 100%),
The background needs to be defined outside of the Container component as the Container has a limited width. The background should be full width.

2023-04-03 20:21 UTC, im-klau commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +    height: 700px;
Feel free to keep hardcoded height sizes for smaller breakpoints. The image can be too small or too large with such values 🙏

2023-04-03 20:22 UTC, im-klau commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +    object-fit: fill;
object-fit: cover is a safer option, take a look at the image now 🙈 😅 

<img width="938" alt="Zrzut ekranu 2023-04-3 o 22 21 43" src="https://user-images.githubusercontent.com/78494852/229618872-7a72d62d-fcc1-4a62-967f-534aadbb0886.png">

2023-04-04 07:50 UTC, AmandaKr commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +  background: linear-gradient(0deg, #eeeeee 0%, rgba(255, 255, 255, 0) 100%),
Additional padding for the background is missing

2023-04-05 06:49 UTC, AmandaKr commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +    object-fit: fill;
I still see this property @Ebmili

2023-04-05 06:52 UTC, AmandaKr commented on packages/design-system/tokens/breakpoints/index.js
> +  tabletImage: 820,
Do we really need this breakpoint? 🤔 tabletLg is enough I thnik

2023-04-05 09:09 UTC, im-klau commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +    padding: 0px auto;
there's no such a property as padding auto 👀 the `auto` values works only for margins

2023-04-05 09:09 UTC, im-klau commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +    padding: 20px auto;
same here

2023-04-05 09:10 UTC, im-klau commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +    height: 100vw;
width and height is duplicated

2023-04-05 09:13 UTC, im-klau commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +    padding: 0;
I think the bottom padding would be beneficial for smaller viewports. Looks like it's missing there.

![Zrzut ekranu 2023-04-5 o 11 12 12](https://user-images.githubusercontent.com/78494852/230036706-1e12fb6a-e95c-4566-92e4-eaa5337cc853.png)

2023-04-05 13:05 UTC, AmandaKr commented on packages/frontend/app/templates/About/components/Values/Values.styled.js
> +    padding-right: 40px;
We have padding left and right set to 24px on mobile and 56px on tablet so you should change it to have our section in one container

2023-04-05 19:56 UTC, AmandaKr approved these changes
good job :rocket:

2023-04-06 08:30 UTC, im-klau approved these changes
The section looks perfect now, and the icons work as expected too! 🎉

2023-04-06 16:03 UTC, merged