fix: introduce fix for the missing map, corrected missing maps
Fundacja-Sterczace-Uszy/website pull request #143
Opened 2023-04-21 20:14 UTC by Ebmili

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description

## Jira issue

JIRA issue: [FSU-XX](https://klau.atlassian.net/browse/FSU-XX)

## Describe your changes

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2023-04-23 09:14 UTC, AmandaKr requested changes

2023-04-23 09:14 UTC, AmandaKr commented on packages/frontend/app/templates/Contact/components/ContactInfo/ContactInfo.jsx
> +        <List gap={8} key={variant}>
The key should be unique, and here it is the same in many places, so you should use another instead of variant, one that does not repeat.  I see that here the elements are repeated, so it might be worth adding an id to each. What do you  think @im-klau?

2023-04-23 09:26 UTC, AmandaKr commented on packages/frontend/app/templates/Contact/components/ContactInfo/ContactInfo.jsx
> +const listData = [
My suggestion is to destructure this object like this, because almost every property in button is the same, only text is different(you can use it for key)

```
const listData = [
  {
    iconName: "phone",
    variant: "gray",
    iconSize: "small",
    text: `${globalData.contact.phoneFirst.text} - sms`,
    link: globalData.contact.phoneFirst.link,
  },
  {
    iconName: "phone",
    variant: "gray",
    iconSize: "small",
    text: `${globalData.contact.phoneSecond.text} - sms`,
    link: globalData.contact.phoneSecond.link,
  },
  {
    iconName: "mail",
    variant: "gray",
    iconSize: "small",
    text: globalData.contact.mail.text,
    link: globalData.contact.mail.link,
  },
]
```
And then map it:
 
```
<List gap={8}>
        {listData.map(({ text, iconName, variant, iconSize, link }) => (
          <ListItem
            key={text}
            iconName={iconName}
            variant={variant}
            iconSize={iconSize}
          >
            <Button
              variant="text"
              text={text}
              size="small"
              color="black"
              href={link}
            />
          </ListItem>
        ))}
      </List>
```

2023-04-25 14:05 UTC, im-klau commented on packages/frontend/app/templates/Contact/components/ContactInfo/ContactInfo.jsx
> +        <List gap={8} key={variant}>
yeah, that's true

@Ebmili always remember that the `key` prop needs to be unique. Basically, keys help React identify which items have changed.

2023-04-25 14:09 UTC, im-klau commented on packages/frontend/app/templates/Contact/components/ContactInfo/ContactInfo.jsx
> +const listData = [
two basic principles: **KISS** - keep it simple, stupid & **DRY** - don't repeat yourself 😄 

Nice idea!

Even the `variant` and `iconSize` props seem to be repeated so I'd get rid of them from the data array and pass them directly to the ListItem.

2023-04-26 20:15 UTC, Ebmili commented on packages/frontend/app/templates/Contact/components/ContactInfo/ContactInfo.jsx
> +        <List gap={8} key={variant}>
@AmandaKr @im-klau this is done

2023-04-26 20:15 UTC, Ebmili commented on packages/frontend/app/templates/Contact/components/ContactInfo/ContactInfo.jsx
> +const listData = [
@im-klau @AmandaKr this is done

2023-05-08 16:12 UTC, im-klau commented on packages/frontend/app/templates/HomePage/components/Actions/Actions.jsx
> +    illustrationName: "help",
You can add another property in each object: `list` and pass those list items simply as text to loop through them in your map.

```
const array = [
 {
   id: "0",
   list: ["item 1", "item 2"]
 }

]

2023-05-08 16:14 UTC, im-klau commented
> @im-klau I did one for the Actions, however, I think there is some issue with styles right now and space between icon and list is too big:( Could you please have a look and advise maybe how can I correct this one?

@Ebmili it looks like those lists aren't placed within the `Card` element as they were before. Moving them inside the Card should help 🤞

2023-05-16 18:14 UTC, Ebmili commented on packages/frontend/app/templates/HomePage/components/Actions/Actions.jsx
> +    illustrationName: "help",
@im-klau just pushed my corrections, however I still have issue with displaying the text from the list : ( I would appreciate some advise on how can I correct this :)

2023-05-17 11:24 UTC, Ebmili commented
> > @Ebmili The PR looks great! Although, I found another section that could be improved the same way 🙈 It's Home/Actions - https://github.com/Fundacja-Sterczace-Uszy/website/blob/FSU-188-datavariable-loops-to-store-multiple-items/packages/frontend/app/templates/HomePage/components/Actions/Actions.jsx
> 
> > 
> 
> > ![Zrzut ekranu 2023-04-28 o 09 49 47](https://user-images.githubusercontent.com/78494852/235087927-1c3e9c85-91ad-4bf7-b438-57f50365e0fb.png)
> 
> > 
> 
> > As you can see, it's similar to the previous ones. The `Card` usage is almost the same, except the `heading` and illustration name so I'd suggest putting only these two values in the data variable.
> 
> 
> 
> @im-klau I did one for the Actions, however, I think there is some issue with styles right now and space between icon and list is too big:( Could you please have a look and advise maybe how can I correct this one?
UPDATE: I think should be fine now ;)

2023-05-19 07:57 UTC, im-klau commented on packages/frontend/app/templates/Contact/components/ContactInfo/ContactInfo.jsx
> +    text: `${globalData.contact.phoneFirst.text} - sms`,
you can simply omit the "$" char and those curly brackets:) same as with the `link` field below this one

2023-05-19 07:57 UTC, im-klau commented on packages/frontend/app/templates/Contact/components/ContactInfo/ContactInfo.jsx
> +    text: `${globalData.contact.phoneSecond.text} - sms`,
you can simply omit the "$" char and those curly brackets:) same as with the `link` field below this one

2023-05-19 07:59 UTC, im-klau commented on packages/frontend/app/templates/HomePage/components/Actions/Actions.jsx
> +    illustrationName: "help",
This is looking nice! 🔥 Although you could simplify the data object a bit more:
Instead of this:
```
  {
    id: "1",
    title: "Chronimy",
    illustrationName: "protect",
    array: [
      {
        id: "1",
        list: [
          "Znajdujemy domy tymczasowe",
          "Szczepimy i budujemy odporność",
          "Szukamy różnych form pomocy",
        ],
      },
    ],
  },
  ```
  
  use:
  
```  
    {
    title: "Chronimy",
    illustrationName: "protect",
    array: [
          "Znajdujemy domy tymczasowe",
          "Szczepimy i budujemy odporność",
          "Szukamy różnych form pomocy",
        ],
  },
  
  when it comes to `id's` required in React in the `key` attribute, you can use the `title` field for example:)

2023-05-19 09:07 UTC, im-klau approved these changes
👏

2023-05-19 09:13 UTC, merged