feat: initialise Panel Component, created Panel Component
Fundacja-Sterczace-Uszy/website pull request #158
Opened 2023-05-26 08:49 UTC by Ebmili

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description

## Jira issue

JIRA issue: [FSU-XX](https://klau.atlassian.net/browse/FSU-XX)

## Describe your changes

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2023-05-26 16:24 UTC, AmandaKr requested changes

2023-05-26 16:24 UTC, AmandaKr commented on packages/design-system/patterns/panelComponent/__stories__/PanelComponent.stories.mdx
> +# PanelComponent
I think `Panel` name  for the component will be enough :D

2023-05-26 16:24 UTC, AmandaKr commented on packages/design-system/patterns/panelComponent/PanelComponent.jsx
> +const PanelComponent = ({ heading, className, title }) => (
You should add also some logic to display the account number etc. as it is described on Jira.

2023-05-26 16:24 UTC, AmandaKr commented on packages/design-system/patterns/panelComponent/PanelComponent.styled.js
> +  padding: 20px 20px 20px 20px;
```suggestion
  padding: 20px;
```

2023-05-26 16:24 UTC, AmandaKr commented on packages/design-system/patterns/panelComponent/PanelComponent.jsx
> +const PanelComponent = ({ heading, className, title }) => (
Also if you add this logic, it would be great to test for example if I add a bank account, the icon is visible.

2023-05-26 16:24 UTC, AmandaKr commented on packages/design-system/patterns/panelComponent/PanelComponent.jsx
> +  heading: string.isRequired,
heading or title? I think better solution will be heading and content :)

2023-05-26 16:24 UTC, AmandaKr commented on packages/design-system/patterns/panelComponent/PanelComponent.styled.js
> +  display: grid;
I will use flex instead of grid, because you need only to display all content by column.
So display:flex and flex-direction: column will be enough.

2023-05-26 16:24 UTC, AmandaKr commented on packages/design-system/patterns/panelComponent/__stories__/PanelComponent.stories.mdx
> +    style={{
Please take a look at how this component looks on Storybook. Try to implement it at is in on Figma because now the component structure is broken down :( 
![image](https://github.com/Fundacja-Sterczace-Uszy/website/assets/97829893/5e45275d-0f18-4f78-bb22-ce72c9e50d8e)

2023-05-26 17:06 UTC, im-klau commented on packages/design-system/patterns/panelComponent/__stories__/PanelComponent.stories.mdx
> +    style={{
I think this is because the Title component has changed recently and you need to update its props (for example variant instead of textSize) 🤔.

2023-05-26 17:11 UTC, im-klau commented on packages/design-system/patterns/panelComponent/__stories__/PanelComponent.stories.mdx
> +          textSize="h6"
take a look at the Title component here -> https://sterczace-uszy-ds.vercel.app/?path=/story/components-title--with-icon

it has different props now:)

2023-05-26 17:11 UTC, im-klau commented on packages/design-system/patterns/panelComponent/__stories__/PanelComponent.stories.mdx
> +    }}
The content of this Panel should be basically anything, can be just children.

2023-05-28 14:57 UTC, Ebmili commented on packages/design-system/patterns/panelComponent/__stories__/PanelComponent.stories.mdx
> +# PanelComponent
@AmandaKr I corrected

2023-05-28 14:59 UTC, Ebmili commented on packages/design-system/patterns/panelComponent/PanelComponent.jsx
> +const PanelComponent = ({ heading, className, title }) => (
@AmandaKr done

2023-05-28 15:01 UTC, Ebmili commented on packages/design-system/patterns/panelComponent/PanelComponent.jsx
> +  heading: string.isRequired,
@AmandaKr I updated to title as it has icon as a prop, heading as children as it is only text and content to show the bottom bank account and iconButton , let me know if it this might be good :)

2023-05-28 15:01 UTC, Ebmili commented on packages/design-system/patterns/panelComponent/PanelComponent.styled.js
> +  display: grid;
@AmandaKr done

2023-05-28 15:01 UTC, Ebmili commented on packages/design-system/patterns/panelComponent/__stories__/PanelComponent.stories.mdx
> +    style={{
@im-klau sorry, I didn't notice this, I updated

2023-05-28 15:01 UTC, Ebmili commented on packages/design-system/patterns/panelComponent/__stories__/PanelComponent.stories.mdx
> +          textSize="h6"
@im-klau this is updated

2023-05-28 15:02 UTC, Ebmili commented on packages/design-system/patterns/panelComponent/__stories__/PanelComponent.stories.mdx
> +    }}
@im-klau I updated to children

2023-05-29 20:43 UTC, AmandaKr commented on packages/design-system/patterns/panelComponent/Panel.jsx
> +  children: string.isRequired,
```suggestion
  title: node.isRequired,
  content: node.isRequired,
  children: node.isRequired,
```

2023-05-29 20:43 UTC, AmandaKr commented on packages/design-system/patterns/panelComponent/index.js
> +import PanelComponent from "./Panel"
change also name of folder to `Panel`

2023-05-29 20:43 UTC, AmandaKr commented on packages/design-system/patterns/panelComponent/Panel.jsx
> +    <Styled.Heading>{children}</Styled.Heading>
I think heading should have our `Title` component  inside, not children. Also with optional icon

2023-05-29 20:43 UTC, AmandaKr commented on packages/design-system/patterns/panelComponent/Panel.jsx
> +      {content}
I may have misled you or vaguely described you, but I think one of the props should be the account number, and if provided, it should have icon with name copy

2023-05-29 20:43 UTC, AmandaKr commented on packages/design-system/patterns/panelComponent/__tests__/Panel.test.jsx
> +describe(`PanelComponent`, () => {
```suggestion
describe(`Panel`, () => {
```

2023-05-29 20:43 UTC, AmandaKr commented on packages/design-system/patterns/panelComponent/__tests__/Panel.test.jsx
> +    expect(screen.getByTitle(icon)).toBeInTheDocument()
You can write second test "renders with custom properties" and add a optional prop to component, take a look for example for example in `IconButton.test.jsx` file

2023-05-30 07:21 UTC, im-klau commented on packages/design-system/patterns/panelComponent/__tests__/Panel.test.jsx
> +    expect(screen.getByTitle(icon)).toBeInTheDocument()
or basically "renders with a bank account number" and verify it the number and the copy icon is visible then 🙌

2023-05-30 07:24 UTC, im-klau commented on packages/design-system/patterns/panelComponent/Panel.jsx
> +      {content}
@Ebmili Just take a look at the acceptance criteria one more time:

> The heading should use the Title component with optional icon.
> The bank account number is also optional. Although, when provided there should be a copy icon added.
> Required fields are: the heading and content (description below the heading).

It means that there are 3 props: title, content (children) and account number.

2023-05-30 09:39 UTC, Ebmili commented on packages/design-system/patterns/panelComponent/Panel.jsx
> +      {content}
@im-klau @AmandaKr I updated to title and children and accountNumber, let me know if this is fine.

2023-05-30 09:42 UTC, Ebmili commented on packages/design-system/patterns/panelComponent/Panel.jsx
> +    <Styled.Heading>{children}</Styled.Heading>
@AmandaKr I updated heading to content as i think it is better to have it inside separate div, it is below title, let me know if this is fine

2023-06-01 07:39 UTC, im-klau commented on packages/design-system/patterns/panelComponent/Panel.jsx
> +  children: node,
these are default props, you cannot use `node` here

2023-06-01 07:39 UTC, im-klau commented on packages/design-system/patterns/panelComponent/__stories__/Panel.stories.mdx
> +Displays important announcements or calls-to-action, usually used above the navigation bar on a website,
Verify this description pls 🙏

2023-06-01 07:40 UTC, im-klau commented on packages/design-system/patterns/panelComponent/__stories__/Panel.stories.mdx
> +      icon: "copy",
there's no `icon` prop, so please remove it from the stories file 🙏

2023-06-01 07:41 UTC, im-klau commented on packages/design-system/patterns/panelComponent/index.js
> +import PanelComponent from "./Panel"
@Ebmili it's about the folder name -> [packages/design-system/patterns/panelComponent/index.js](https://github.com/Fundacja-Sterczace-Uszy/website/pull/158/files#diff-b601d391169920c8a075de1776f368267cc57903bedab28baa0967ae02cc1613)

It should be `patterns/panel`

2023-06-02 08:14 UTC, AmandaKr commented on packages/design-system/patterns/panel/__stories__/Panel.stories.mdx
> +Displays informaiton about Bank transfer,
Please fix typo and commas at the end of this sentence

2023-06-02 08:15 UTC, im-klau commented on packages/design-system/patterns/panel/Panel.jsx
> +      {accountNumber && <IconButton name="copy" />}
@Ebmili the copy button should indeed copy the bank account number 🙈

2023-06-02 08:15 UTC, im-klau commented on packages/design-system/patterns/panel/Panel.jsx
> +  accountNumber: node,
```suggestion
  accountNumber: string,
```

2023-06-02 08:17 UTC, im-klau commented on packages/design-system/patterns/panel/Panel.jsx
> +      {accountNumber && <IconButton name="copy" />}
the icon isn't aligned with the text

![Zrzut ekranu 2023-06-2 o 10 17 27](https://github.com/Fundacja-Sterczace-Uszy/website/assets/78494852/387bb998-6fc9-4c6e-b2da-48d46e89553e)

2023-06-02 08:18 UTC, im-klau commented on packages/design-system/patterns/panel/__stories__/Panel.stories.mdx
> +      iconName: "copy",
there's no `iconName` prop so you can remove it

2023-06-02 08:21 UTC, im-klau reviewed
@Ebmili pls, do your own final code review 🙏 

Take a look at the "files changed" tab, here, in Github and verify all your changes.

It looks like the component is almost ready to be merged, although there are some small bugs that could be easily fixed 🙌

2023-06-03 13:03 UTC, Ebmili commented on packages/design-system/patterns/panel/Panel.jsx
> +      {accountNumber && <IconButton name="copy" />}
@im-klau Hi, I added the function, let me know If this is fine. Also, I added pop-up to diplay ,,Skopiowano" so the user knows that the the bank account is copied, but let me know If this needed actually, I think usually there is some alert, but maybe we don't need it.

2023-06-04 12:58 UTC, AmandaKr commented on packages/design-system/patterns/panel/Panel.jsx
> +  const [isCopied, setIsCopied] = useState(false)
Please use our `useCopyToClickboard` hook

2023-06-04 12:58 UTC, AmandaKr commented on packages/design-system/patterns/panel/__stories__/Panel.stories.mdx
> +# Panel Displays information about Bank transfer.
Description should be under # Panel text, so it should be:
# Panel
Displays information about Bank transfer.

2023-06-04 12:58 UTC, AmandaKr commented on packages/design-system/patterns/panel/Panel.styled.js
> +  float: left;
It would be better to not use float, take a look how icon and copy info are styling in `Donation.styled.js `:D

2023-06-04 20:01 UTC, Ebmili commented on packages/design-system/patterns/panel/Panel.styled.js
> +  float: left;
@AmandaKR updated as per Donation.Styled

2023-06-05 14:35 UTC, im-klau approved these changes
🚀

2023-06-05 14:43 UTC, merged