feat: fsu-45 badge component
Fundacja-Sterczace-Uszy/website pull request #17
Opened 2022-10-01 07:41 UTC by nconnect1789

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description

## Jira issue

JIRA issue: [FSU-45](https://klau.atlassian.net/browse/FSU-XX)

## Describe your change

Added badge component with corresponding emotion styled component file.
Added storybook file and created stories for badge component.
Added jest tests for badge component.

## Checklist before requesting a review

- [x] Checked which branch you would merge.
- [x] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [x] Performed a self-review of code (bugs, clean code rules, etc).
- [x] Checked if added variables have unique names.
- [x] Checked if added code/function is not a duplicate. 
- [x] Tests have been added if possible.
- [x] New and existing unit tests pass locally with my changes.

2022-10-01 10:13 UTC, paulgrym reviewed
Good job! Just a few changes in styles and it would be great :)

2022-10-01 10:13 UTC, paulgrym commented on packages/design-system/components/badge/Badge.styled.js
> +  align-items: center;
We need to set font as in the design

2022-10-01 10:13 UTC, paulgrym commented on packages/design-system/components/badge/__tests__/Badge.test.jsx
> +import userEvent from "@testing-library/user-event"
This import is never used

2022-10-01 10:13 UTC, paulgrym commented on packages/design-system/components/badge/__tests__/Badge.test.jsx
> +  it(`renders the budge with text`, () => {
Typo - should be "badge":)

2022-10-01 10:13 UTC, paulgrym commented on packages/design-system/components/badge/Badge.jsx
> +import React from "react"
I'm not sure whether this import is necessary

2022-10-01 10:14 UTC, im-klau commented on packages/design-system/components/badge/Badge.styled.js
> +  align-items: center;
yup, "Poppins" font family is missing

2022-10-01 10:20 UTC, im-klau commented on packages/design-system/components/badge/__tests__/Badge.test.jsx
> +  it(`renders the budge with text`, () => {
![Zrzut ekranu 2022-10-1 o 12 17 17](https://user-images.githubusercontent.com/78494852/193404607-0ee81f1a-7fbf-4890-9059-a34f7b9a8e52.png)

It's always worth reading tests as they were just english sentences, for example:
`Badge renders with default properties` - seems 100% fine, but reading: `Badge renders the badge with text` doesn't make sense

2022-10-01 10:20 UTC, im-klau commented
Super clean PR, nice description, only 4 files changes, easy to read and understand 🙌 ❤️

2022-10-01 10:25 UTC, im-klau requested changes

2022-10-01 10:25 UTC, im-klau commented on packages/design-system/components/badge/__tests__/Badge.test.jsx
> +  it(`renders the budge with text`, () => {
I'm thinking about these two tests now and maybe you can change the second one to "renders with custom properties" - so that we can make sure `variant` and `size` works, it wouldn't be about `text` anymore, since the `text` property is required and it's tested in the first case

So it would be:
1. renders with default properties - as it is now
2. renders with custom properties - just the name of the test needs to be changed, the render method is fine

2022-10-03 10:48 UTC, nconnect1789 commented on packages/design-system/components/badge/Badge.styled.js
> +export const Badge = styled.span`
I changed it to div 😃 
As we agreed, I am leaving the font and line-height until they are set in our theme file.

2022-10-03 10:49 UTC, nconnect1789 commented on packages/design-system/components/badge/Badge.styled.js
> +  align-items: center;
Done :)

2022-10-03 10:53 UTC, nconnect1789 commented on packages/design-system/components/badge/__tests__/Badge.test.jsx
> +  it(`renders the budge with text`, () => {
It seems much more better, thanks 😄

2022-10-03 10:56 UTC, nconnect1789 commented on packages/design-system/components/badge/Badge.styled.js
> +export const Badge = styled.span`
Thanks for the tips 😄

2022-10-04 11:17 UTC, im-klau approved these changes

2022-10-04 11:17 UTC, im-klau commented on packages/design-system/components/badge/Badge.styled.js
> +  ${({ size }) => {
this line will be enough as soon as we merge the Typography V2 version, the line-height property shouldn't be needed as well then (it's needed now)

nice work! 🙌

2022-10-04 11:22 UTC, merged