feat: introduce Volunteering Section, added Volunteering Section to t…
Fundacja-Sterczace-Uszy/website pull request #178
Opened 2023-07-05 18:51 UTC by Ebmili

## Jira issue

JIRA issue: [FSU-271](https://klau.atlassian.net/browse/FSU-271)

## Describe your changes
This pull introduces Volunteering Section for the Support Page. 

## Checklist before requesting a review

- [x] Checked which branch you would merge.
- [x] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [x] Performed a self-review of code (bugs, clean code rules, etc).
- [x] Checked if added variables have unique names.
- [x] Checked if added code/function is not a duplicate. 
- [x] Tests have been added if possible.
- [x] New and existing unit tests pass locally with my changes.

2023-07-06 07:37 UTC, im-klau commented
@Ebmili it looks like there's an accessibility error, you need to run Cypress/e2e tests locally in order to see what's going on 😄 

![Zrzut ekranu 2023-07-6 o 09 36 17](https://github.com/Fundacja-Sterczace-Uszy/website/assets/78494852/8ace02fc-0386-4b7d-b833-99dd3338198b)

2023-07-09 17:19 UTC, AmandaKr commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +export const TextBottomWrapper = styled.div`
You don't use it anywhere, is it needed?

2023-07-09 17:19 UTC, AmandaKr commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  display: grid;
It seems to me that you don't need all these grid-related properties here. `Feature` component has all the styles you need.

2023-07-09 17:19 UTC, AmandaKr commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +      <Styled.ContainerSection as="section" role="main">
Container component doesn't have role prop

2023-07-13 17:57 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  display: grid;
@AmandaKr I actually tried with display: flex, but I think in this case grid is better, to diplay - especially in combination with top image-text and svg in the second row, however, please advise if yoou have other suggestions :)

2023-07-13 17:59 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +export const TextBottomWrapper = styled.div`
@AmandaKr actually I use it for the volunteering-image at the top.

2023-07-13 18:00 UTC, Ebmili commented on packages/design-system/tokens/illustrations/behaviorist.svg
@AmandaKr this is done.

2023-07-14 08:03 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +          subtitle="WOLONTARIAT"
@AmandaKr done

2023-07-14 08:03 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +            Choć w prowadzenie Fundacji wkładamy całe serce, wciąż brakuje nam
@AmandaKr done

2023-07-14 08:04 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +          alt="dog with heart"
@AmandaKr I corrected :)

2023-07-14 08:04 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +          tabletLayout="right"
@AmandaKr this one also done : )

2023-07-14 08:04 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +          size="medium"
@AmandaKr doen

2023-07-14 08:04 UTC, Ebmili commented on packages/design-system/tokens/illustrations/behaviorist.svg
@AmandaKr good catch, thanks deleted them

2023-07-14 08:05 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +      <Styled.ContainerSection as="section" role="main">
@AmandaKr I deleted

2023-07-16 07:43 UTC, paulgrym commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +          alt="volunteering"
alt prop should be in site language

2023-07-17 06:45 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +          alt="volunteering"
@paulgrym I updated, please let me know If this is what you mean?

2023-07-17 06:54 UTC, paulgrym commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +          alt="volunteering"
No, I meant it should be in Polish ;) 
Aslo now there is eslint warning:
> Replace `␍⏎··········src="../support/volunteering-image.png"·alt=""␍⏎·······` with `·src="../support/volunteering-image.png"·alt=""`eslint[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)

2023-07-17 07:03 UTC, paulgrym requested changes

2023-07-17 07:03 UTC, paulgrym commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  margin-left: 120px;
Adding margin-left: 120px; to center the Button is a bad idea. Button should be always centered - not only one particular screen width

2023-07-17 08:41 UTC, im-klau commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +          alt="volunteering"
If the image is just like a decorative asset, the `alt` should be empty:)

2023-07-17 09:16 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +          alt="volunteering"
@paulgrym @im-klau I just updated to PL version. @im-klau this is about the image on the top, so not really decorative one I think :)

2023-07-17 09:16 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +            size="medium"
@paulgrym I updated :)

2023-07-17 09:16 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  margin-left: 120px;
@paulgrym updated.

2023-07-18 13:52 UTC, im-klau requested changes

2023-07-18 13:52 UTC, im-klau commented on packages/design-system/components/illustration/Illustration.jsx
> +import Photograph from "design-system/tokens/illustrations/photograph.svg"
@Ebmili We have the Camera illustration already, which is the same as the one you've just added :D

2023-07-18 13:52 UTC, im-klau commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +  ]
Storing constant data inside the component function may impact performance and code readability. 

For better maintainability, it's recommended to define such constant data outside the component function. This way, we avoid unnecessary reinitialization and make the code easier to understand and modify in the future 🙏

2023-07-18 13:52 UTC, im-klau commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  gap: 230px;
this gap size seems to be quite large:) also, this element isn't event a grid/flex container so the gap doesn't work

2023-07-18 13:52 UTC, im-klau commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +
The Illustration prop is defined in the Feature component so the Feature should be responsible for keeping the size, not a section.

2023-07-18 13:52 UTC, im-klau commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  margin-left: 0px;
It's just a div, it doesn't have any margin so there's no need to use 0px value here.

2023-07-20 10:40 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +        <Styled.ImageWrapper>
@im-klau this is done

2023-07-20 10:40 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +        <Styled.Img src="../support/volunteering-image.png" alt="Wolontariat" />
@im-klau done

2023-07-20 10:40 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  margin-left: 0px;
@im-klau removed

2023-07-20 10:40 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  }
@im-klau I removed

2023-07-20 10:41 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +
@im-klau I defined separate styling for the illustration only, so it does not take icon background and has fixed sizes within the feature component. Please let me know if this would be fine.

2023-07-20 10:47 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  gap: 230px;
@im-klau I removed

2023-07-20 10:47 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +  ]
@im-klau updated and will not e for the future, thanks :)

2023-07-20 10:47 UTC, Ebmili commented on packages/design-system/components/illustration/Illustration.jsx
> +import Photograph from "design-system/tokens/illustrations/photograph.svg"
@im-klau  removed :)

2023-07-21 10:12 UTC, im-klau commented on packages/design-system/patterns/feature/Feature.styled.js
> +  width: 80px;
according to the design, it should be 100px:)

2023-07-21 10:13 UTC, im-klau commented on packages/design-system/components/illustration/Illustration.jsx
> -      height="100%"
@Ebmili you don't need to remove these values, it's okay to have these % defined here + pixels value in a component (Feature for example)

2023-07-21 10:15 UTC, im-klau commented
@Ebmili  the `photograph.svg` illustration is still there :D

2023-07-21 16:11 UTC, Ebmili commented on packages/design-system/components/illustration/Illustration.jsx
> -      height="100%"
@im-klau this is done

2023-07-21 16:11 UTC, Ebmili commented on packages/design-system/patterns/feature/Feature.styled.js
> +  width: 80px;
@im-klau I corrected

2023-07-22 15:28 UTC, AmandaKr commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +        </Typography>
You can use map here

2023-07-22 15:28 UTC, AmandaKr commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +        </List>
You don't need to use `List` and `ListItem` components here, `Feature` will be enough

2023-07-22 15:28 UTC, AmandaKr commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +        </Styled.Title>
```suggestion    
          <Styled.TitleText="Kogo szukamy?" variant="h3" />
```
and then overwrite the styles in styled.js

2023-07-22 15:28 UTC, AmandaKr commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  margin-top: 50px;
```suggestion
margin: 50px auto 0;
```

2023-07-22 15:28 UTC, AmandaKr commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +    grid-template-columns: 1fr;
As I mentioned before, imo you don't need this all grid properties, flex will be enough and you won't need so much code :D but up to you :)

2023-07-22 15:28 UTC, AmandaKr commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  }
You can get rid of it, it's totally redundant

2023-07-22 15:28 UTC, AmandaKr commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  padding-bottom: 30px;
```suggestion
export const TitleText = styled(Title)`
  padding-top: 50px;
  padding-bottom: 30px;
```

2023-07-24 07:17 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +        </List>
@AmandaKr I used List as feature component doesn't have any gaps between and as per design we need some. I think I cna get rid of them, but anyway some extra div will be need to provide gaps.

2023-07-24 07:55 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  }
@AmandaKr Actually I don't think all code here is redundant :) I need to have different width for the tablet and mobile, and also grid-row property. I reduced the code a bit by deleted the columns properties.

2023-07-24 11:31 UTC, AmandaKr commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +        </List>
You can just add a container for it and add display: flex and flex-direction: column + gap instead of using List and ListItem. Look at my PR I have there the same case 
<img width="276" alt="image" src="https://github.com/Fundacja-Sterczace-Uszy/website/assets/97829893/66447041-46cd-4d9a-be7e-1b3c38aba472">

2023-07-27 19:41 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  padding-bottom: 30px;
@AmandaKr this is done

2023-07-27 19:41 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +    grid-template-columns: 1fr;
@AmandaKr updated with flex :)

2023-07-27 19:42 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  margin-top: 50px;
@AmandaKr corrected.

2023-07-27 19:42 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +        </List>
@AmandaKr So, I did :)

2023-07-27 19:42 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.jsx
> +        </Typography>
@AmandaKr this is done

2023-07-30 15:13 UTC, AmandaKr approved these changes

2023-07-30 15:13 UTC, AmandaKr commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  padding-top: 10px;
```suggestion
  padding-top: 120px;
```

2023-07-30 15:13 UTC, AmandaKr commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  width: 90%;
```suggestion
max-width: 385px;
```

2023-07-31 10:48 UTC, im-klau approved these changes

2023-07-31 16:36 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  width: 90%;
@AmandaKr done

2023-07-31 16:37 UTC, Ebmili commented on packages/frontend/app/templates/Support/components/Volunteering/Volunteering.styled.js
> +  padding-top: 10px;
@AmandaKr done

2023-07-31 17:38 UTC, Ebmili commented
> @Ebmili the `photograph.svg` illustration is still there :D

2023-08-01 18:54 UTC, merged