feat: Button component
Fundacja-Sterczace-Uszy/website pull request #19
Opened 2022-10-02 09:20 UTC by paulgrym

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description

## Jira issue

JIRA issue: [FSU-46](https://klau.atlassian.net/browse/FSU-46)

## Describe your changes

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2022-10-02 10:34 UTC, im-klau commented on packages/design-system/components/link/Button.jsx
> +  link,
`href` could be a better name as it's really a href attribute :D

2022-10-02 10:36 UTC, im-klau commented on packages/design-system/components/link/Button.styled.js
> +  letter-spacing: -0.02em;
all fonts styles should be from the `theme`, you should be able to access them via:
```
export const Component = styled.div`
  ${({ theme }) => theme.typography.desktop.h4}
  
  // other css tyles
`

2022-10-06 09:45 UTC, im-klau commented on packages/design-system/components/button/Button.jsx
> +import { string, oneOf, func, bool, shape } from "prop-types"
It looks like the Button is almost ready to review 🚀 
We're just waiting for some unit tests 👀

2022-10-06 12:40 UTC, im-klau requested changes
I left some small comments, but overall nice work!! 🙌 

It's a super clean code 🎉

2022-10-06 12:40 UTC, im-klau commented on packages/design-system/components/button/Button.jsx
> +        <iconStart.icon />
the `<iconStart.icon />` doesn't make sense anymore, there was an onClick function before, but now it's just an icon so you can use `iconStart` prop

2022-10-06 12:40 UTC, im-klau commented on packages/design-system/components/button/Button.jsx
> +        <iconEnd.icon />
the `<iconEnd.icon />` doesn't make sense anymore, there was an onClick function before, but now it's just an icon so you can use `iconEnd` prop

2022-10-06 12:40 UTC, im-klau commented on packages/design-system/components/button/Button.jsx
> +      as={href ? `a` : `button`}
this logic could be a good case for testing, to make sure that when `href` is provided the componen is a link, not a button and the other way

2022-10-06 12:40 UTC, im-klau commented on packages/design-system/components/button/Button.styled.js
> +  color: ${({ variant, color }) =>
It seems like you defined the color already in the Component. Can you make sure this one is needed too? I think it can be inherited from the parent element but I'm not 100% sure.

2022-10-06 12:40 UTC, im-klau commented on packages/design-system/components/button/Button.styled.js
> +  cursor: pointer;
the Icon element is inside the Link which has the cursor: pointer property, it's not needed here anymore

2022-10-06 12:40 UTC, im-klau commented on packages/design-system/components/button/Button.styled.js
> +  background-color: transparent;
it's a span, not a button, are these two lines still needed?

2022-10-06 12:40 UTC, im-klau commented on packages/design-system/components/button/Button.jsx
> +    {iconStart && (
make sure to include `iconStart` and `iconEnd` props in testing, so that we can make sure the element is rendered when a prop is passed 🙏

2022-10-06 19:55 UTC, paulgrym commented on packages/design-system/components/button/Button.styled.js
> +  background-color: transparent;
You're right, it's left over from the old concept when icons were buttons, I'm removing it

2022-10-10 11:37 UTC, im-klau commented on packages/design-system/components/button/__tests__/Button.test.jsx
> +    render(<Button text={text} iconStart={MockIcon} />)
the assert line is missing, are you sure the icon is rendered? this test will succeed even if you remove the `iconStart` from the button component

you can simply use the `toBeInTheDocument()` you used before

2022-10-10 11:37 UTC, im-klau commented on packages/design-system/components/button/__tests__/Button.test.jsx
> +    render(<Button text={text} iconEnd={MockIcon} />)
the same issue here

2022-10-10 11:38 UTC, im-klau commented on packages/design-system/components/button/Button.styled.js
> +  color: ${({ variant, color }) =>
hmm I'd say the `Link` name is fine, you can leave it as it is now:)

2022-10-10 11:42 UTC, im-klau commented on packages/design-system/components/button/__tests__/Button.test.jsx
> +import userEvent from "@testing-library/user-event"
I love how you managed to test all the different features of this component! 
I'm impressed 👏 ❤️

2022-10-13 08:53 UTC, im-klau commented on packages/design-system/components/button/__tests__/Button.test.jsx
> +    expect(screen.getByTestId("icon-end")).toBeInTheDocument()
could you add this test id to the MockIcon only? I think it's not needed to add it somewhere inside the Button component 🤔

2022-10-13 09:05 UTC, im-klau commented on packages/design-system/components/button/__tests__/Button.test.jsx
> +    expect(screen.getByTestId("icon-end")).toBeInTheDocument()
This is my last change request, I promise hahah 😂 Button is going to be merged, finally 🚀

2022-10-13 14:24 UTC, paulgrym commented on packages/design-system/components/button/__tests__/Button.test.jsx
> +    expect(screen.getByTestId("icon-end")).toBeInTheDocument()
Done 😄 Please, check if that is what you meant 😅

2022-10-13 16:43 UTC, nconnect1789 approved these changes
Great job 🚀

2022-10-15 14:09 UTC, AmandaKr approved these changes
Well done 😍

2022-10-15 17:11 UTC, merged