Fsu 47 annoucementbanner
Fundacja-Sterczace-Uszy/website pull request #28
Opened 2022-10-11 10:11 UTC by Emilia123x

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description

## Jira issue

JIRA issue: [FSU-47](https://klau.atlassian.net/browse/FSU-47)

## Describe your changes

Hi,
I am afraid I need some help. I some corrections are still needed, however I have no idea why my component is now not showing in storybook. Yesterday it was working, today I copied it and created new branch for pull request and it suddenly dissapeared. Can this be an issue with copying, or there are other mistakes in the code? 

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2022-10-11 12:50 UTC, im-klau commented on packages/design-system/components/annoucementbanner/__stories__/annoucementbanner.stories.mdx
> +export const Template = (args) => <Button {...args} />
```suggestion
export const Template = (args) => <Annoucementbanner {...args} />
```

it should be `Annoucementbanner`, not `Button` - that's why Storybook didn't work:)

2022-10-11 12:59 UTC, im-klau requested changes

2022-10-11 12:59 UTC, im-klau commented on packages/design-system/components/annoucementbanner/__stories__/annoucementbanner.stories.mdx
> +      iconEnd: <ArrowDownIcon />,
these two props could be combined in one: `button` - this way we could pass a ready to use component: `button: <Button text="button" iconEnd={<ArrowDownIcon />} />` and that's all :D 

or...I think the content of the Announcement Banner could be set as `children`:
```
<Annoucementbanner>
  Nasi podopieczni czekają na Twoje wsparcie! Chcesz nam pomóc? Zajrzyj <Button text="tutaj" />
</Annoucementbanner>
```

2022-10-11 12:59 UTC, im-klau commented on packages/design-system/components/annoucementbanner/Annoucementbanner.jsx
> +)
could you verify you're Pull Request once again? It looks like Button, not AnnoucementBanner :<

2022-10-12 14:53 UTC, Emilia123x commented on packages/design-system/components/annoucementbanner/Annoucementbanner.jsx
> +)
This is done, I 've prepared new draft. FYI I set up the arrow as the ,,button""within the ,,banner" section, can I please ask if this makes more sense?

2022-10-14 07:44 UTC, im-klau commented on packages/design-system/components/annoucementbanner/Annoucementbanner.jsx
> +import { string, oneOf, func, bool, node } from "prop-types"
Yeah, shorter name Banner is even better. Thank you!:)

2022-10-14 07:46 UTC, im-klau commented
Let's just wait for the Button component to be merged 🙏 Then, we can reuse this component here, in the Banner so that it will replace the Link styled component you've just created

2022-10-16 10:39 UTC, paulgrym requested changes
Nice job 😄 Only tests are missing out 😉

2022-10-16 10:39 UTC, paulgrym commented on packages/design-system/components/banner/Banner.styled.js
> +  }
Redundant curly bracket

2022-10-16 10:39 UTC, paulgrym commented on packages/design-system/components/badge/Badge.styled.js
> +        return theme.colors.ncomplementary[100]
typo- "ncomplementary" should be "complementary" instead

2022-10-16 10:39 UTC, paulgrym commented on packages/design-system/components/banner/Banner.styled.js
> +  position: relative;
When reducing the screen width, the link separates from the banner text, so I would remove 
``` display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  position: relative;
```
and then I would add to Banner ` text-align: center;` and to Heading `display: inline;`

2022-10-16 10:45 UTC, im-klau commented on packages/design-system/components/badge/Badge.styled.js
> +        return theme.colors.ncomplementary[100]
that's weird, the Badge component shouldn't change in this PR at all 🤔

2022-10-16 19:52 UTC, Emilia123x commented on packages/design-system/components/banner/Banner.styled.js
> +  }
this is done :)

2022-10-17 13:06 UTC, im-klau requested changes

2022-10-17 13:06 UTC, im-klau commented on packages/design-system/components/badge/Badge.styled.js
> +        return theme.colors.ncomplementary[100]
@Emilia123x could you revert these changes? the Badge component shouldn't change in this PR 🙏

2022-10-17 13:06 UTC, im-klau commented on packages/design-system/components/banner/Banner.jsx
> +    {button && button}
```suggestion
    {button}
```

2022-10-17 13:06 UTC, im-klau commented on packages/design-system/components/banner/__tests__/Banner.test.jsx
> +import { render, screen, act } from "../../../test-utils"
@Emilia123x take a look at the Eslint warning here, the `act` function is not needed

2022-10-17 16:23 UTC, im-klau requested changes

2022-10-17 16:23 UTC, im-klau commented on packages/design-system/components/badge/Badge.styled.js
> +        return theme.colors.ncomplementary[100]
this is still a valid issue ⚠️

2022-10-18 07:47 UTC, nata-kab commented on packages/design-system/components/banner/Banner.styled.js
> +  }
Please check again. 🙃 I can still see the addition curly bracket 🔍

2022-10-18 08:00 UTC, nata-kab commented on packages/design-system/components/banner/__tests__/Banner.test.jsx
> +})
Well done 🚀 Just one test should be added (whether the button is displayed) 😉

2022-10-18 08:15 UTC, nata-kab commented on packages/design-system/components/banner/Banner.styled.js
> +  }
The header and button are not in line. It looks like the header text is not in the Header center🕵️‍♀️ 
Please check it 😉 
![Screenshot 2022-10-18 at 09 35 42](https://user-images.githubusercontent.com/60882127/196375105-0fbfc8c3-9469-442e-aa21-dc43e3c779f1.png)
![Screenshot 2022-10-18 at 10 05 55](https://user-images.githubusercontent.com/60882127/196375160-3ab1dd11-01f1-483d-80e7-a8c477624641.png)

2022-10-18 08:19 UTC, nata-kab commented on packages/design-system/components/banner/Banner.styled.js
> +  }
I can still see the addition curly bracket 🔍  🙃

2022-10-18 10:58 UTC, im-klau commented on packages/design-system/components/banner/__tests__/Banner.test.jsx
> +})
oh true, great idea!

2022-10-18 10:59 UTC, im-klau commented on packages/design-system/components/banner/__stories__/Banner.stories.mdx
> +<Meta title="Components/Banner" Banner={Banner} />
```suggestion
<Meta title="Components/Banner" component={Banner} />
```

2022-10-19 18:48 UTC, AmandaKr approved these changes

2022-10-20 08:05 UTC, nata-kab approved these changes
🚀

2022-10-20 20:41 UTC, paulgrym commented on packages/design-system/components/banner/__tests__/Banner.test.jsx
> +})
Small error in this test 
![image](https://user-images.githubusercontent.com/87578610/197053654-bdd35e45-6369-4ad1-b76c-7e9145585980.png)

2022-10-20 20:42 UTC, paulgrym commented on packages/design-system/components/banner/__tests__/Banner.test.jsx
> +})
Small error in this test 
![image](https://user-images.githubusercontent.com/87578610/197053871-bc6a3842-d340-4000-9e4b-d4c2a55e8f4a.png)

2022-10-21 10:12 UTC, im-klau commented on packages/design-system/components/banner/__tests__/Banner.test.jsx
> +})
it's weird, this kind of an error should fail while CI in Github Actions :D

2022-10-21 14:32 UTC, nata-kab commented on packages/design-system/components/banner/__tests__/Banner.test.jsx
> +})
I think that Github Actions passed because all test passed. Weird.🤔
<img width="649" alt="Screenshot 2022-10-21 at 16 31 59" src="https://user-images.githubusercontent.com/60882127/197220963-7e8933a1-d59a-4b07-af27-7dca7f92d69b.png">

2022-10-22 09:55 UTC, im-klau commented on packages/design-system/components/banner/__tests__/Banner.test.jsx
> +})
yeah, that's true, all of the tests passed so that's fine, but there was a console error anyway and I think we should make the CI fail when there's an error (even if all tests succeed), for example when a prop is required but someone didn't provide it

I found a package that can handle that - https://github.com/ValentinH/jest-fail-on-console (probably :D)

But this could be a future improvement 🤞

2022-10-22 09:56 UTC, im-klau commented on packages/design-system/components/banner/__tests__/Banner.test.jsx
> +})
@Emilia123x only one, small bug here, the `heading` prop is missing in the second test case 👀 Other than that it looks perfect now 🎉

2022-10-24 09:08 UTC, paulgrym approved these changes

2022-10-24 12:07 UTC, merged