feat: create input component
Fundacja-Sterczace-Uszy/website pull request #61
Opened 2022-12-11 20:56 UTC by paulgrym

## Jira issue

JIRA issue: [FSU-78](https://klau.atlassian.net/browse/FSU-78)

## Describe your changes

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2022-12-12 17:21 UTC, im-klau commented on packages/design-system/theme/theme.js
> +      success: "#14AE5C",
Just in order to keep consistency, I'd follow the number rule, so:
```jsx
    decorative: {
      100: "#0D99FF",
      success: {
         100:  "#14AE5C"
     }
```

I'm not sure what to do with the `decorative[100]` color though 🤔

2022-12-12 17:23 UTC, im-klau commented on packages/design-system/components/icon/Icon.jsx
> +  success: Success,
I think there's a `done` icon already, which probably can be used in the input valid state 🤔

2022-12-13 21:54 UTC, paulgrym commented on packages/design-system/components/icon/Icon.jsx
> +  success: Success,
done icon has less free space around the actual icon 😓

2022-12-13 21:57 UTC, paulgrym commented on packages/design-system/theme/theme.js
> +      success: "#14AE5C",
ok, changed 😄

2022-12-14 10:07 UTC, im-klau requested changes

2022-12-14 10:07 UTC, im-klau commented on packages/design-system/components/input/__tests__/Input.test.jsx
> +    expect(screen.getByRole("textbox")).toBeInTheDocument()
wooaa `textbox`, nice!! 👏

2022-12-14 10:10 UTC, im-klau commented on packages/design-system/components/input/__tests__/Input.test.jsx
> +      <Input label={label} disabled placeholder="Example placeholder text" />
I feel like there's not much sense in passing props that aren't needed for a particular test case. I mean the placeholder 🤪 

But overall, I love all of your tests! 😍

2022-12-14 10:15 UTC, im-klau commented on packages/design-system/theme/theme.js
>      decorative: {
Oh, one more thing about the theme colors - they don't work in Storybook anymore 😂 
https://design-system-git-fsu-78-input-fsu.vercel.app/?path=/story/theme--page

2022-12-14 14:03 UTC, im-klau commented on packages/design-system/components/input/Input.jsx
> +    <Styled.LabelText>{label}</Styled.LabelText>
shouldn't this be the Typography component with a proper variant? 🤔

2022-12-14 14:03 UTC, im-klau commented on packages/design-system/components/input/Input.jsx
> +    <Styled.Message required={required} data-testid="message">
shouldn't this be the Typography component with a proper variant? 🤔

2022-12-14 21:35 UTC, paulgrym commented on packages/design-system/components/input/Input.styled.js
> +  min-height: 22.4px;
Ok, good idea :D

2022-12-14 21:36 UTC, paulgrym commented on packages/design-system/components/input/__tests__/Input.test.jsx
> +      <Input label={label} disabled placeholder="Example placeholder text" />
You are right, placeholder prop wasn't supposed to be here 😅

2022-12-14 21:43 UTC, paulgrym commented on packages/design-system/components/input/Input.jsx
> +    <Styled.LabelText>{label}</Styled.LabelText>
Yes, it should 😅 I totally forgot about that component 🤦‍♀️

2022-12-14 21:44 UTC, paulgrym commented on packages/design-system/theme/theme.js
>      decorative: {
I see what you mean - I will look closely at our theme colors gallery code 🕵️‍♀️

2022-12-15 15:06 UTC, im-klau commented on packages/design-system/components/icon/Icon.jsx
> +  success: Success,
Oh, probably they should be unified somehow, but let's leave the new one as it is. We'll get back to this issue...next year 😂 And we'll solve it in a separate PR

2022-12-15 22:33 UTC, paulgrym commented on packages/design-system/components/input/Input.jsx
> +    <Styled.Message required={required} data-testid="message">
Now I have one problem - how to pass data-testId to message when I use Typography component? 😅

2022-12-28 15:23 UTC, im-klau approved these changes

2023-01-03 16:44 UTC, nata-kab commented on packages/design-system/components/input/__stories__/Input.stories.mdx
> +    {Template.bind()}
Looks good 😀 You could use the Canvas for each component, this is the best practice to show multiple examples in Storybook .

2023-01-03 16:46 UTC, nata-kab commented
Well done! 👏 🚀

2023-01-04 15:21 UTC, im-klau commented on packages/design-system/components/input/__stories__/Input.stories.mdx
> +    {Template.bind()}
oooh, nice catch Natalia! 

I totally agree, one Canvas per component should be better 🙈 
![Zrzut ekranu 2023-01-4 o 14 16 53](https://user-images.githubusercontent.com/78494852/210563588-14bbf8e1-d0a4-4be9-8bb2-52c38129b6e0.png)

2023-01-06 14:22 UTC, AmandaKr approved these changes
You have done great job, code is clean and everything works fine 🚀 !

2023-01-06 16:18 UTC, merged