FSU-89-Accordion
Fundacja-Sterczace-Uszy/website pull request #68
Opened 2023-01-05 19:31 UTC by Ebmili

Co-authored-by: Klaudia <78494852+im-klau@users.noreply.github.com>

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description

## Jira issue

JIRA issue: [FSU-XX](https://klau.atlassian.net/browse/FSU-XX)

## Describe your changes

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2023-01-05 19:32 UTC, Ebmili reviewed
Hi, please kindly review my component. As said, still working on styles :)

2023-01-06 10:54 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.jsx
> +  inactiveIcon: string,
take a look at task's description:
<img width="655" alt="Zrzut ekranu 2023-01-6 o 11 50 07" src="https://user-images.githubusercontent.com/78494852/210997826-e28de330-7ce5-4b66-9055-fa492e4efacf.png">

there's no need to set these icons as properties because they should stay the same forever:D

Also, there could be only one icon that will be rotated on click. Simply use transform in CSS:)

2023-01-06 10:54 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.jsx
> +  variant: oneOf(["primary", "main", "neutrals"]),
I'd name this prop `color` as it's related to colors only:)

2023-01-06 10:57 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.jsx
> +  button: null,
There's no need to pass a button as a prop, using children should be enough.

As a child you can pass any component you want to:
```jsx
<Accordion>
    <List>
        <ListItem>
          O nas
        </ListItem>
        <ListItem >
          Aktualnosci
        </ListItem>
     <List>
     <Button>Jakiś przykładowy button</Button>
</Accordion>
```

2023-01-06 10:58 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.jsx
> +  required: bool,
why do you need this `required` prop?

2023-01-06 10:59 UTC, im-klau commented on packages/design-system/components/accordion/__stories__/Accordion.stories.mdx
> +<Meta title="Components/Accordion" component={Accordion} />
```suggestion
<Meta title="Recipes/Accordion" component={Accordion} />
```

2023-01-15 16:00 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.styled.js
> +  float: right;
don't use floats, please 🙏 let's use flex, or CSS grid if needed

2023-01-15 16:19 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.styled.js
> +  border-radius: 10px;
border-radius is duplicated

2023-01-15 16:20 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.styled.js
> +  height: 50%;
I'm not sure why 50%, since it should be full width, meaning 100%. When it comes to height, it's always a good practice not to define it, as the height of any element should depend on its content

2023-01-15 16:21 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.styled.js
> +  height: 50%;
the same situation with height 50% here, there's no need to define it

2023-01-15 16:21 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.styled.js
> +  display: block;
you used `display: block` but there are other flex properties below

2023-01-15 16:22 UTC, im-klau commented on packages/design-system/components/accordion/__stories__/Accordion.stories.mdx
> +      icon: "arrowUp",
the `icon` prop isn't needed anymore

2023-01-15 16:24 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.jsx
> +    <Icon name={icon}/>
use a hardcoded name for the icon, there's no need to pass it as a prop as the Accordion should use the same icon:
```jsx
<Icon name="arrowDown"/>
```

2023-01-15 16:24 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.jsx
> +    {button}
a button should be provided with children, there's no need to define it as a separate prop

2023-01-16 00:37 UTC, Ebmili commented on packages/design-system/components/accordion/Accordion.jsx
> +    {button}
This is done.

2023-01-16 00:37 UTC, Ebmili commented on packages/design-system/components/accordion/Accordion.jsx
> +    <Icon name={icon}/>
done.

2023-01-16 00:38 UTC, Ebmili commented on packages/design-system/components/accordion/Accordion.styled.js
> +  height: 50%;
Deleted, set to 100%.

2023-01-16 00:39 UTC, Ebmili commented on packages/design-system/components/accordion/Accordion.styled.js
> +  height: 50%;
Deleted, set to 100%.

2023-01-16 00:42 UTC, Ebmili commented on packages/design-system/components/accordion/Accordion.jsx
> +  activeColor: oneOf(["primary", "neutrals", "grey", "white", "white with Button", "white with Links" ]),
Hi, I simplified this to white, black, primary and neutrals, because I think that for the title it is needed to have them defined, so title has primary option for white and black. Pleaase let me know, If  this looks good.

2023-01-16 08:45 UTC, im-klau commented on packages/design-system/components/accordion/__tests__/Accordion.test.jsx
> +describe(`Badge`, () => {
I guess it should be Accordion, not Badge anymore 😅

2023-01-16 08:54 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.styled.js
> +    }
you defined the background color for the Title and for the Content separately, but it may be worth using this element `export const Accordion = styled.div` to define the background only once

this way we could simplify the code a bit more, as Title and Content always have the same background color

2023-01-16 08:55 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.styled.js
> +  float: right;
float combined with flex 👀

2023-01-16 08:55 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.styled.js
> +  width: 100%;
duplicated width property

2023-01-16 08:56 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.styled.js
> +  gap: 100px;
the gap doesn't work as this element doesn't use flex/grid

2023-01-18 16:51 UTC, Ebmili commented on packages/design-system/components/accordion/Accordion.styled.js
> +  border-radius: 10px;
this is done.

2023-01-18 17:29 UTC, Ebmili commented on packages/design-system/components/accordion/__tests__/Accordion.test.jsx
> +describe(`Badge`, () => {
This is done.

2023-01-20 16:24 UTC, im-klau requested changes

2023-01-20 16:24 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.styled.js
> +  border-radius: 10px;
background color and box shadow should be added to the Accordion here only, because there's a weird box shadow now:
![Zrzut ekranu 2023-01-20 o 17 19 48](https://user-images.githubusercontent.com/78494852/213750000-ee5984e9-4447-4225-aecb-d1d2228e4c3b.png)

☝️ this is because there are two separate elements with background colors and box shadows.

Remove shadows and background colors from the Title and Content pls 🙏

2023-01-20 16:24 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.styled.js
> +  ${({ activeColor, color }) =>
the icon is rotated by default:
![Zrzut ekranu 2023-01-20 o 17 22 44](https://user-images.githubusercontent.com/78494852/213750564-ab8d36da-e7b5-4612-bb65-e4b66dcb61bb.png)

as you can see on the screenshot, it's rotated as the accordion would be active, but it's not 😅

2023-01-20 16:24 UTC, im-klau commented on packages/design-system/components/accordion/__stories__/Accordion.stories.mdx
> +import { Meta, Canvas, Story, ArgsTable } from "@storybook/addon-docs"
take a look at this file, please 🙏 it has some eslint errors still

2023-01-20 16:24 UTC, im-klau commented on packages/design-system/components/accordion/__stories__/Accordion.stories.mdx
> +<Meta title="Components/Accordion" component={Accordion} />
@Ebmili you can click the "Commit suggestion" button here to apply my suggestion about the title :D

2023-01-21 09:57 UTC, Ebmili commented on packages/design-system/components/accordion/Accordion.styled.js
> +  border-radius: 10px;
This is done.

2023-01-22 10:02 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.styled.js
> +  border-radius: 10px;
there's still box-shadow added to the Content, take a look at the line 54 in this file 👀

2023-01-22 10:05 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.styled.js
> +      transform: rotate(180deg);
The icon should rotate based on the active state, not the activeColor prop. If you want to change something based on a prop, the prop needs to change somehow, but the `activeColor` has always the same value 😅 so the icon will never be rotated

2023-01-22 10:07 UTC, im-klau commented on packages/design-system/components/accordion/__stories__/Accordion.stories.mdx
> +import { Meta, Canvas, Story, ArgsTable } from "@storybook/addon-docs"
if mdx linting doesn't work in your VSC that's probably because you forgot to add additional settings, it should be done based on this PR https://github.com/Fundacja-Sterczace-Uszy/website/pull/72

![Zrzut ekranu 2023-01-22 o 11 06 07](https://user-images.githubusercontent.com/78494852/213910284-85349e5e-b60c-4bde-b916-ea72191ff159.png)

If you don't want to do this, simply run "yarn lint" in your terminal to get all the errors so that you'll be able to fix them. Some basic ones can be fixed automatically by running `yarn lint --fix`

2023-01-22 14:04 UTC, AmandaKr requested changes

2023-01-22 14:04 UTC, AmandaKr commented on packages/design-system/components/accordion/Accordion.jsx
> +      <Styled.Title
Shouldn't we use Title from our `<Title/>` component? 🤔

2023-01-23 07:11 UTC, Ebmili commented on packages/design-system/components/accordion/Accordion.jsx
> +      <Styled.Title
Hi, I can't use title, because it doesn't have relevant styles for the red title color :)

2023-01-23 07:13 UTC, Ebmili commented on packages/design-system/components/accordion/Accordion.styled.js
> +      transform: rotate(180deg);
Hi, I tried, to do this with isActive prop and still no sucess :( I have commited the way I was using it, so you can maybe check and advise on this?

2023-01-23 08:37 UTC, AmandaKr commented on packages/design-system/components/accordion/Accordion.jsx
> +      <Styled.Title
but you can override this adding className prop like we have there `packages/design-system/recipes/textBanner/TextBanner.styled.js`

2023-01-23 12:18 UTC, AmandaKr commented on packages/design-system/components/accordion/Accordion.styled.js
> +  transform: ${(props) => (props.isActive ? "rotate(180deg)" : "rotate(0)")};
```
 transform: ${props => props.isActive ? "rotate(180deg)" : "rotate(0)"};
```

2023-01-23 12:18 UTC, AmandaKr commented on packages/design-system/components/accordion/Accordion.styled.js
> +  transform: ${(props) => (props.isActive ? "rotate(180deg)" : "rotate(0)")};
This is not working, maybe try this solution

2023-01-23 15:27 UTC, Ebmili commented on packages/design-system/components/accordion/Accordion.styled.js
> +  transform: ${(props) => (props.isActive ? "rotate(180deg)" : "rotate(0)")};
@AmandaKr Tried this way, also no success. Actually prettier changes it into: transform: ${(props) => (props.isActive ? "rotate(180deg)" : "rotate(0)")}; I cannot use your version :( DO you have any other idea how this can be solved?

2023-01-24 15:36 UTC, im-klau commented on packages/design-system/components/accordion/Accordion.jsx
> +      <Styled.Title
It's not possible to use the Title component as it has different sizes, but it was possible to use the Typography with `h4` variant 🙌

2023-02-15 09:10 UTC, im-klau commented on packages/design-system/components/accordion/__tests__/Accordion.test.jsx
> +    render(<Accordion name={iconName} />)
According to the props there's no `variant` and `name` 🤔 and you're using them in your tests

![Zrzut ekranu 2023-02-15 o 10 09 13](https://user-images.githubusercontent.com/78494852/218983408-df7c538a-1ef9-49fb-82b5-a85a13ccbd9d.png)

2023-02-15 09:13 UTC, im-klau requested changes

2023-02-15 09:13 UTC, im-klau commented on packages/design-system/components/accordion/__tests__/Accordion.test.jsx
> +})
It would be nice to add a test about the main logic/functionality which is opening/closing the Accordion. You can use the `userEvent` function to handle that.

You need an element that will be clicked (the one that handles the onClick event in the Accordion) and then you can verify if the body: `<Styled.Content>{children}</Styled.Content>` is visible using something like `.toBeInTheDocument()` 

![Zrzut ekranu 2023-02-15 o 10 10 36](https://user-images.githubusercontent.com/78494852/218983706-38759a26-508f-4ba1-a735-c1e9874fc7e1.png)

2023-02-21 09:08 UTC, im-klau approved these changes

2023-02-21 09:15 UTC, merged