fix(iconButton): missing target prop
Fundacja-Sterczace-Uszy/website pull request #77
Opened 2023-01-16 19:21 UTC by KlaudiaBrzywcy

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description
Fix icon-Button missing target prop
## Jira issue

JIRA issue: [FSU-102](https://klau.atlassian.net/browse/FSU-102)

## Describe your changes
added missing target prop to IconButton (the same as in HTML like target=_blanc)

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2023-01-19 09:16 UTC, im-klau requested changes

2023-01-19 09:16 UTC, im-klau commented on .env.example
> -NODE_ENV=
the file is still here 🙈

2023-01-21 18:19 UTC, im-klau commented on .env.example
> +APP_KEYS=IP/TTdeR5D5ZlPgy21CKag==,D1wyCeSyFHgzBqhsqfcoqA==,yJAmEkfS8z/gmVrrmt1ufA==,VH5gF53XJ+IK0/bi9EjLLQ==
```suggestion
APP_KEYS=
```

2023-01-21 18:19 UTC, im-klau commented on .env.example
> +API_TOKEN_SALT=A72anEyzTYrvWaoPlRS0ow==
```suggestion
API_TOKEN_SALT=
```

2023-01-21 18:20 UTC, im-klau commented on .env.example
> +HOST=0.0.0.0
```suggestion
HOST=
```

2023-01-21 18:20 UTC, im-klau commented on .env.example
> +MY_HEROKU_URL=https://sterczace-uszy.herokuapp.com
```suggestion
```

2023-01-21 18:20 UTC, im-klau commented on .env.example
> +NODE_ENV=development
```suggestion
NODE_ENV=
```

2023-01-21 18:20 UTC, im-klau commented on .env.example
> +PORT=1337
```suggestion
PORT=
```

2023-01-22 10:17 UTC, im-klau commented on .env.example
> +API_TOKEN_SALT=
```suggestion
API_TOKEN_SALT=
ADMIN_JWT_SECRET=
JWT_SECRET=
```

2023-01-22 10:54 UTC, im-klau approved these changes
I forgot this is a public repo and that's why I resolved env issue on my own 😅

2023-01-22 13:24 UTC, AmandaKr approved these changes
🎉

2023-01-23 18:27 UTC, merged