feat: create Select component
Fundacja-Sterczace-Uszy/website pull request #78
Opened 2023-01-19 21:00 UTC by paulgrym

## Jira issue

JIRA issue: [FSU-90](https://klau.atlassian.net/browse/FSU-90)

## Describe your changes
Select component added. 
Problem: clicking on custom arrow-down area doesn't open the options

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2023-01-22 10:41 UTC, im-klau requested changes
Well, I thought this component would be more difficult 😅 
I left a few (improvement) comments 🤞

2023-01-22 10:41 UTC, im-klau commented on packages/design-system/components/select/Select.jsx
> +            <option key={option}>{option}</option>
based on the [mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select):
> Each <option> element should have a [value](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#attr-value) attribute containing the data value to submit to the server when that option is selected.

I think this is missing but we would need it in order to get the selected item when submitting a form 🤔 
Or any other way that will allow us to get the data.

2023-01-22 10:41 UTC, im-klau commented on packages/design-system/components/select/Select.jsx
> +        <Icon name="arrowDown" size="medium" />
I'm not sure if it's possible to do this (since this component is uncontrolled and we don't have any state), but if the option list is longer, the icon is still visible and it's not rotated 🙈 

![Zrzut ekranu 2023-01-22 o 11 28 51](https://user-images.githubusercontent.com/78494852/213911232-d339b033-a23c-4cd3-8b11-a5ca3f923a1d.png)

If it's not possible to solve this, that's fine 👍

2023-01-22 10:41 UTC, im-klau commented on packages/design-system/components/select/Select.styled.js
> +  top: 19px;
Using pixel values when centering an element isn't very safe as every time you update the parent element styles you need to remember to update these values too.

I'd use `top: 50%` and `transform: translateY(-50%)` to make sure it's always centered. This would require removing margin from the select as the icon is positioned based on it.

Also, maybe try adding `display: inline-flex` to this styled.span element because its size isn't the same as the icon's size.
![Zrzut ekranu 2023-01-22 o 11 38 02](https://user-images.githubusercontent.com/78494852/213911583-299d46bf-2d59-483b-9601-9a74b427c48c.png)

2023-01-22 10:41 UTC, im-klau commented on packages/design-system/components/select/__tests__/Select.test.jsx
> +describe(`Select`, () => {
Are we able to test if options are visible only after clicking the select? 🤔 
Additional test could be about checking the selected value.

2023-01-29 09:56 UTC, paulgrym commented on packages/design-system/components/select/__tests__/Select.test.jsx
> +describe(`Select`, () => {
I didn't manage to check visibility with ".toBeVisible" - all options seem to be "visible" from the start 🤔 
But I've added the test with checking the selected value :)

2023-01-29 19:34 UTC, AmandaKr approved these changes
Well done 🚀

2023-01-29 19:34 UTC, AmandaKr commented on packages/design-system/components/select/__tests__/Select.test.jsx
> +describe(`Select`, () => {
You can check if options are visible that way:
` options.forEach((option) => {
      expect(getByText(option)).toBeInTheDocument()
    })`

2023-01-30 08:38 UTC, im-klau commented on packages/design-system/components/select/__tests__/Select.test.jsx
> +  it(`renders with first option selected, changes selected value to chosen option  `, () => {
I'd split this test into two, separate ones. The first one could simply check if the first option is selected, and the second one could verify if selecting behavior works

2023-01-31 10:39 UTC, im-klau approved these changes

2023-01-31 10:59 UTC, merged