feat: update colors v3 in theme
Fundacja-Sterczace-Uszy/website pull request #82
Opened 2023-01-23 17:51 UTC by nata-kab

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description

## Jira issue

JIRA issue: [FSU-120](https://klau.atlassian.net/browse/FSU-120)

## Describe your changes

Update colors in theme.

## Checklist before requesting a review

- [x] Checked which branch you would merge.
- [x] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [x] Performed a self-review of code (bugs, clean code rules, etc).
- [x] Checked if added variables have unique names.
- [x] Checked if added code/function is not a duplicate. 
- [x] Tests have been added if possible.
- [x] New and existing unit tests pass locally with my changes.

2023-01-24 10:16 UTC, AmandaKr approved these changes

2023-01-24 14:07 UTC, im-klau requested changes

2023-01-24 14:07 UTC, im-klau commented on packages/design-system/theme/theme.js
> +      100: "##FAF4F4",
there's a duplicated "#" char 🙈

2023-01-24 14:07 UTC, im-klau commented on packages/design-system/theme/theme.js
> +      600: "##0C0C0C",
there's a duplicated "#" char 🙈

2023-01-25 10:22 UTC, nata-kab commented on packages/design-system/theme/theme.js
> +      100: "##FAF4F4",
Thanks for catching this 🙈

2023-01-26 09:15 UTC, im-klau approved these changes

2023-01-26 15:15 UTC, merged