feat: navigation
Fundacja-Sterczace-Uszy/website pull request #88
Opened 2023-02-13 15:23 UTC by im-klau

## Name PR according scheme: type of changes (feat/fix/refactor etc.) + description
feat: navigation

## Jira issue

JIRA issue: [FSU-29](https://klau.atlassian.net/browse/FSU-29)

## Describe your changes
This PR introduces the Navigation (without dropdowns).
The code is ready to review, however the background color can change in the future.

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

2023-02-19 19:08 UTC, paulgrym requested changes

2023-02-19 19:08 UTC, paulgrym commented on packages/design-system/blocks/navigation/Navigation.styled.js
> +  }
The is no nav between 744 and 1200px

2023-02-20 11:06 UTC, im-klau commented on packages/design-system/blocks/navigation/Navigation.styled.js
> +  }
oh my... 🙈

2023-02-20 18:30 UTC, paulgrym approved these changes
⭐

2023-02-21 09:21 UTC, merged